### PR TITLE
Pipe table and table caption support (witiko/markdown backport)

### PR DESCRIPTION
**Pull request by Omikhleia**
This PR is the backport to lunamark of Vít Novotný's pipe table support from the witiko/markdown project.
(https://github.com/Witiko/markdown)

Note: witiko/markdown is now LPPL-licensed, but these improvements were added when the project was still MIT-licensed.

See #31 for context.

I also added support for these to the HTML writer, so that to provide a non-regression test case. The HTML output mimics that from Pandoc in terms of output, class and styles.

### CODE REVIEW

**Comment by Witiko** [comment]
Nice work. I glanced over the changes and here is a minor nitpick: the extension is called `pipe_table` and claims to be named the same as Pandoc's extension for pipe tables, but in fact, Pandoc's extension for pipe tables is called `pipe_tables` (plural).

**Comment by Omikhleia** [comment]
> Nice work.

Thanks, so all credits are yours, it quite a straightforward back-port ;)

> However, Pandoc's extension for pipe tables is called `pipe_tables` (plural).

Oops, that's right. Shouldn't we follow the same name as in Pandoc, just for homogeneity? I.e. change it to `pipe_tables`?

(N.B. I'm leaving for vacations in the countryside tomorrow, not sure how network connectivity will be there... There's no urge, though!)

**Comment by Witiko** [comment]
> Shouldn't we follow the same name as in Pandoc, just for homogeneity? I.e. change it to `pipe_tables`?

That's what I would do, but it's a minor complaint. Let me know when the PR is ready, so that I can do a proper review.

**Comment by Omikhleia** [comment]
Changed `pipe_table` option to `pipe_tables`

**Comment by Witiko** [comment]
Looks good, thanks again!

**Pull request merged**
