### PR TITLE
Upload release to luarocks when a new version tag is pushed

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by tarleb** [comment]
To use this, one first needs to create a Luarocks API key here: https://luarocks.org/settings/api-keys

That key should then be added as a secret with name `API_KEY` here: https://github.com/jgm/lunamark/settings/secrets/actions

**Comment by tarleb** [comment]
This is a bit ad-hoc and could probably be improved, but it should work.

**Comment by jgm** [comment]
I want to wait a bit on this til I'm more comfortable with the release process (doing it manually).

Meanwhile, tests are messed up now (I guess because I changed the Makefile to use `--local`, which is needed on my system).  Can you see how to fix?

**Comment by alerque** [comment]
The @lunarmodules org repostiry has some reusable workflows that are a bit more robust than this for seeing when rockspecs changes, testing them against multiple versions of Lua & LuaRocks, then publishing them if everything succeeds. I've used them for several projects outside of that org namespace and they can be used as steps pretty easily anywhere. If you're interested in automatically publishing to LuaRocks I can submit a workflow that uses those tools.

**Comment by jgm** [comment]
Sure, I'd be happy to consider that (of course it would depend on the details -- all things considered I like to keep things simple and avoid depending on things that might break).

**Pull request closed without merging**
